### ISSUE TITLE
C-GQA test open_world

### ISSUE THREAD

**Issue by PanXGzhu** [jingchenchen/RAPR#2]
I encountered an error related to "CUDA OUT OF MEMORY" when testing C-GQA in an open-world setting. However, the other two datasets worked fine both in open-world and closed-world tests, and C-GQA also ran smoothly in the closed-world test. May I ask if you have ever encountered this issue before?
![image](https://github.com/user-attachments/assets/83072cae-41cd-4dad-9d78-133b5c9622d1)

**Comment by PanXGzhu** [comment]
/home/px/miniconda3/envs/rapr/bin/python /home/px/code/RAPR-main/test.py --dataset cgqa --open_world True 
evaluation details
----
dataset: cgqa
loading validation dataset
# train pairs: 5592 | # val pairs: 2292 | # test pairs: 1811
# train images: 26920 | # val images: 7280 | # test images: 5098
loading test dataset
# train pairs: 5592 | # val pairs: 2292 | # test pairs: 1811
# train images: 26920 | # val images: 7280 | # test images: 5098
<All keys matched successfully>
evaluating on the validation set
Evaluating with validation pairs
Testing:   0%|                                                                                                               | 0/1820 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/px/code/RAPR-main/test.py", line 608, in <module>
    all_logits, all_attr_gt, all_obj_gt, all_pair_gt, loss_avg = predict_logits(
  File "/home/px/code/RAPR-main/test.py", line 406, in predict_logits
    predict = model(batch_img, pairs)
  File "/home/px/miniconda3/envs/rapr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/px/code/RAPR-main/model/rapr_model.py", line 226, in forward
    text_features, _ = self.text_encoder(self.token_ids,token_tensors,enable_pos_emb=self.enable_pos_emb,)
  File "/home/px/miniconda3/envs/rapr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/px/code/RAPR-main/model/common.py", line 55, in forward
    text_feature = self.transformer(x)
  File "/home/px/miniconda3/envs/rapr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/px/code/RAPR-main/model/backbone.py", line 87, in forward
    return self.resblocks(x)
  File "/home/px/miniconda3/envs/rapr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/px/miniconda3/envs/rapr/lib/python3.8/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/home/px/miniconda3/envs/rapr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/px/code/RAPR-main/model/backbone.py", line 167, in forward
    x = x + self.attention(self.ln_1(x))
  File "/home/px/miniconda3/envs/rapr/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/px/code/RAPR-main/model/backbone.py", line 17, in forward
    ret = super().forward(x.type(torch.float32))
  File "/home/px/miniconda3/envs/rapr/lib/python3.8/site-packages/torch/nn/modules/normalization.py", line 189, in forward
    return F.layer_norm(
  File "/home/px/miniconda3/envs/rapr/lib/python3.8/site-packages/torch/nn/functional.py", line 2347, in layer_norm
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: CUDA out of memory. Tried to allocate 6.37 GiB (GPU 0; 23.69 GiB total capacity; 14.71 GiB already allocated; 4.23 GiB free; 17.91 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

进程已结束，退出代码为 1

**Comment by PanXGzhu** [comment]
![image](https://github.com/user-attachments/assets/df91b822-6915-4b47-9a4d-44995c547555)
![image](https://github.com/user-attachments/assets/95e20989-6469-4488-a9fb-075e21e71b2a)

**Comment by jingchenchen** [comment]
The reason is that the C-GQA dataset has a huge number of compositions in the open-world setting. You can try to encode the text representations of the compositions in batches instead of encoding them at once.

**Comment by PanXGzhu** [comment]
Hey, I'm new to machine learning and this is my first time trying to recreate a paper from it. I really don't want to quit and want to do it as well as I can. But since I'm just starting, my coding might not be great. How should I go about fixing my code? Can you help me with that?

**Comment by jingchenchen** [comment]
You can split the testing compositions into vairous batches, and encode them batch by batch. 
Below is an example of using CLIP to encode texts in batches that you can refer to. 

```python
from transformers import CLIPTokenizer, CLIPModel
import torch

def encode_texts_in_batches(texts, batch_size=128):
    
    # Encode multiple texts using CLIP and process them in batches.    
    # param texts: List[str], the list of texts to encode
    # param batch_size: int, the number of texts in each batch
    # return: List[torch.Tensor], the encoded text vectors

    # Load the CLIP model and tokenizer
    model_name = "openai/clip-vit-base-patch32"
    tokenizer = CLIPTokenizer.from_pretrained(model_name)
    model = CLIPModel.from_pretrained(model_name)

    # Set the model to evaluation mode
    model.eval()

    # Split texts into batches
    num_batches = (len(texts) + batch_size - 1) // batch_size
    encoded_texts = []

    for i in range(num_batches):
        # Get the texts for the current batch
        batch_texts = texts[i * batch_size: (i + 1) * batch_size]
        
        # Tokenize the texts
        inputs = tokenizer(batch_texts, padding=True, truncation=True, return_tensors="pt")
        
        # Encode the texts with CLIP
        with torch.no_grad():
            text_features = model.get_text_features(**inputs)
            encoded_texts.append(text_features)

        print(f"Processed batch {i + 1}/{num_batches}")

    # Concatenate all encoded results from batches
    all_encoded_texts = torch.cat(encoded_texts, dim=0)
    return all_encoded_texts


# Example: Generate a set of texts
texts = [f"Text sample {i}" for i in range(12800)]  # Total 12800 texts, 128 per batch

# Call the function to encode texts
encoded_texts = encode_texts_in_batches(texts, batch_size=128)

# Output the shape of the encoded results
print("Encoded texts shape:", encoded_texts.shape)
```

**Comment by PanXGzhu** [comment]
Thank you for your answer. I have one more question. What is the process from training images to creating the two databases?

**Comment by jingchenchen** [comment]
Pleas refer to "download_data/build_db.py". Thanks.
